### ISSUE TITLE
how to compile it

### ISSUE THREAD

**Issue by xshion13** [weiwu1994/LordsBot#1]
Hello, i want to know wich version of visual studio is needed or wich steps is necessary to compile and test it. also a little instrucction about what files modify in order to improve this software. thanks! :9

**Comment by weiwu1994** [comment]
I was using Microsoft Visual Studio 2017 when writing the code. I believe any version would work though.

The concept is to use OpenCV's image processing library to perform image detection. This would be the bots "eyes".

The "hands" of the bot is performed using Windows32 I/O API, to send key/mouse clicks to any where on the screen or a specific window container on the screen without interfering with the actual mouse pointer.

So using those two concepts it is literally possible to automate/bot anything. It is a brutal force method so speed is a main issue.

The main goal of the project was to make it undetectable by the game that it bots. and to be customizable to bot any game as long as it can be run on windows OS somehow.

The project is a bit outdated because the script hasn't been updated in a while. As the game changes/updates the script will need to be updated as well otherwise the bot will not be able to detect locations of buttons that it should be clicking in the game.

The compiled program will not work correctly at the moment since the game that it was meant to automate has updated to many times since i last worked on this project. 

However the main functions like image detection and I/O functions can be tested separately and will work. 

I'll fix everything up when i got the time.
